# Generated by Django 3.1.2 on 2020-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20201029_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.SlugField(choices=[('frontend', 'Фронтенд разработка'), ('backend', 'Бэкенд разработка'), ('gamedev', 'Разработка игр'), ('devops', 'Девопс'), ('design', 'Дизайн'), ('products', 'Продукты'), ('management', 'Менеджмент'), ('testing', 'Тестирование')], default='backend', unique=True),
        ),
    ]
